version: "3.8"

services:  
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - network1

  jackson:
    image: "boxyhq/jackson"
    depends_on:
      - postgres
    ports:
      - 5000:5000
    environment:
      - JACKSON_API_KEYS=secret
      - DB_ENGINE=sql
      - DB_TYPE=postgres
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres
    networks:
      - network1

  supertoken:
    image: "registry.supertokens.io/supertokens/supertokens-postgresql"
    depends_on:
      - postgres
    ports:
      - 3567:3567
    environment:
      - POSTGRESQL_CONNECTION_URI=postgres://postgres:postgres@postgres:5432/postgres
    networks:
      - network1

  app:
    build: ./app
    ports:
      - 3000:3000
    networks:
      - network1

  api:
    build: ./api
    ports:
      - 4000:4000
    networks:
      - network1

networks:
  network1: